[package]
name = "pukka"
version = "0.1.0"
authors = ["bgoodman <b@thebgoodman.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.15.0"
clipboard = "0.5.0"
rand = "0.7.3"
